### ISSUE TITLE
Perceptual_loss?

### ISSUE THREAD

**Issue by Mid-Push** [VeroHU/verovero_perceptual_loss_for_SR#1]
Hi, when will u back home and have dinner? It's very late

**Comment by VeroHU** [comment]
I have to work overtime tonight, maybe I will sleep in the company.

**Comment by VeroHU** [comment]
Hi, what do u want to eat tonight? I will go to the supermarket after class

**Comment by Mid-Push** [comment]
I like pork and beef. Remember to get some grapes and pineapples.

**Comment by VeroHU** [comment]
good idea！I will！
so，do u like my cooking？

**Comment by Mid-Push** [comment]
yes, i love your cooking and u.

**Comment by VeroHU** [comment]
thx，i love u too

**Comment by Mid-Push** [comment]
how are you? Will you come home for lunch?

**Comment by VeroHU** [comment]
I have finished my work and now I am coming home. wait me!

**Comment by Mid-Push** [comment]
Good. Remember to buy yabo and malaxiangguo!

**Comment by VeroHU** [comment]
1111111

**Comment by VeroHU** [comment]
hello, I miss u, and I love u

**Comment by Mid-Push** [comment]
I'm here. Wait for me at home and I will come back soon! Love u!

**Comment by VeroHU** [comment]
嘤嘤嘤

**Comment by VeroHU** [comment]
where is my man? my man is in my dream

**Comment by Mid-Push** [comment]
Your man is here! Give me a hug. Mua ❤️

**Comment by Mid-Push** [comment]
I love u. My dear wife.

**Comment by VeroHU** [comment]
what r u talking about？today i am not your wife， ok？

**Comment by Mid-Push** [comment]
You are my darling. You are my wife forever.

**Comment by VeroHU** [comment]
really?

**Comment by VeroHU** [comment]
hi, excuse me? I was wondering how to add the emoji?

**Comment by VeroHU** [comment]
what happened to you, my darling? why don't u reply to me?

**Comment by Mid-Push** [comment]
Hello! I'm here! Your lover is here!  my jio choujinger le. Please come here to save me.

**Comment by VeroHU** [comment]
no, bufuzadi?!

**Comment by Mid-Push** [comment]
hey, how is it going? My wife, go home for dinner!

**Comment by VeroHU** [comment]
Fine, thanks. I will go to the pub to bengdi with my sisters tonight.  don't wait for me, darling

**Comment by Mid-Push** [comment]
Please go home quickly. You have 8 kids at home waiting for you cooking.

**Comment by Mid-Push** [comment]
my dear wife. How are you?

**Comment by VeroHU** [comment]
But I know nothing about cooking!!! what can I do ??? my dear!!!

**Comment by VeroHU** [comment]
please star my new repository please!!!
